spring.application.name=alpha-hotel

spring.datasource.url=jdbc:postgresql://localhost:5432/alpha_hotelDb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a8fb28001@smtp-brevo.com
spring.mail.password=YOxmJEwPVh5tbB2s
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

server.port=8080

app.jwt.secret=alphaHotelCleSecreteAlphaHotelCleSecrete2025
app.jwt.expiration-ms=86400000
app.mail.from=rianaravelontsoa@gmail.com
app.mail.notification-admin=rianaravelontsoa@gmail.com
app.scheduler.auto-checkout-cron=0 10 0 * * *
app.scheduler.depart-reminder-cron=0 0 18 * * *
app.scheduler.admin-depart-summary-cron=0 0 7 * * *
